server:
  error:
    include-stacktrace: never
    
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    user:
      name: client-user
      password: password123
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include: "*"