server:
  port: 8282
  
spring:
  application:
    name: currency-conersion-service
  cloud:
    config:
      import-check:
        enabled: false
#  jpa:
#    show-sql: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:tdb
#  h2:
#    console:
#      enabled: true
