server:
  port: 8282
  
spring:
  application:
    name: currency-conersion-service
  cloud:
    config:
      import-check:
        enabled: false

---      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka